local unit = require 'llx.unit'
local llx = require 'llx'
local Seq = llx.Seq

_ENV = unit.create_test_env(_ENV)

describe('Seq', function()
  describe('construction', function()
    it('should accept a function iterator', function()
      local s = Seq(llx.functional.range(1, 4))
      expect(s:count()).to.be_equal_to(3)
    end)

    it('should accept a plain sequence-shaped table', function()
      local s = Seq({10, 20, 30})
      expect(s:count()).to.be_equal_to(3)
    end)

    it('should accept a List directly', function()
      local s = Seq(llx.List{1, 2, 3})
      expect(s:count()).to.be_equal_to(3)
    end)

    it('should reject unsupported sources', function()
      expect(function() Seq(42) end).to.throw()
      expect(function() Seq('hi') end).to.throw()
    end)
  end)

  describe('map / filter / collect chain', function()
    it('should chain map then filter then collect', function()
      local out = Seq({1, 2, 3, 4, 5})
        :map(function(x) return x * x end)
        :filter(function(x) return x > 4 end)
        :collect()
      expect(#out).to.be_equal_to(3)
      expect(out[1]).to.be_equal_to(9)
      expect(out[2]).to.be_equal_to(16)
      expect(out[3]).to.be_equal_to(25)
    end)

    it('reject should keep elements failing the predicate', function()
      local out = Seq({1, 2, 3, 4})
        :reject(function(x) return x % 2 == 0 end)
        :collect()
      expect(#out).to.be_equal_to(2)
      expect(out[1]).to.be_equal_to(1)
      expect(out[2]).to.be_equal_to(3)
    end)
  end)

  describe('take / drop', function()
    it('take should yield the first n elements', function()
      local out = Seq({1, 2, 3, 4, 5}):take(3):collect()
      expect(#out).to.be_equal_to(3)
      expect(out[3]).to.be_equal_to(3)
    end)

    it('take 0 should yield empty', function()
      local out = Seq({1, 2, 3}):take(0):collect()
      expect(#out).to.be_equal_to(0)
    end)

    it('take more than length should yield all', function()
      local out = Seq({1, 2}):take(10):collect()
      expect(#out).to.be_equal_to(2)
    end)

    it('drop should skip the first n', function()
      local out = Seq({1, 2, 3, 4, 5}):drop(2):collect()
      expect(out[1]).to.be_equal_to(3)
      expect(out[3]).to.be_equal_to(5)
    end)

    it('drop more than length should yield empty', function()
      local out = Seq({1, 2}):drop(10):collect()
      expect(#out).to.be_equal_to(0)
    end)
  end)

  describe('take_while / drop_while', function()
    it('take_while should stop at first failure', function()
      local out = Seq({1, 2, 3, 1, 2})
        :take_while(function(x) return x < 3 end)
        :collect()
      expect(#out).to.be_equal_to(2)
      expect(out[1]).to.be_equal_to(1)
      expect(out[2]).to.be_equal_to(2)
    end)

    it('drop_while should keep everything after first failure', function()
      local out = Seq({1, 2, 3, 1, 2})
        :drop_while(function(x) return x < 3 end)
        :collect()
      expect(#out).to.be_equal_to(3)
      expect(out[1]).to.be_equal_to(3)
    end)
  end)

  describe('flat_map', function()
    it('should flatten one level', function()
      local out = Seq({1, 2, 3})
        :flat_map(function(x) return {x, x * 10} end)
        :collect()
      expect(#out).to.be_equal_to(6)
      expect(out[1]).to.be_equal_to(1)
      expect(out[2]).to.be_equal_to(10)
      expect(out[3]).to.be_equal_to(2)
      expect(out[6]).to.be_equal_to(30)
    end)
  end)

  describe('distinct', function()
    it('should remove duplicates', function()
      local out = Seq({1, 2, 2, 3, 1, 4}):distinct():collect()
      expect(#out).to.be_equal_to(4)
      expect(out[1]).to.be_equal_to(1)
      expect(out[2]).to.be_equal_to(2)
      expect(out[3]).to.be_equal_to(3)
      expect(out[4]).to.be_equal_to(4)
    end)

    it('should use a key function when provided', function()
      local out = Seq({'apple', 'avocado', 'banana', 'blueberry'})
        :distinct(function(s) return s:sub(1, 1) end)
        :collect()
      expect(#out).to.be_equal_to(2)
      expect(out[1]).to.be_equal_to('apple')
      expect(out[2]).to.be_equal_to('banana')
    end)
  end)

  describe('tap', function()
    it('should call fn with each element and pass through', function()
      local seen = {}
      local out = Seq({1, 2, 3})
        :tap(function(v) seen[#seen + 1] = v end)
        :map(function(v) return v * 10 end)
        :collect()
      expect(seen[1]).to.be_equal_to(1)
      expect(seen[3]).to.be_equal_to(3)
      expect(out[3]).to.be_equal_to(30)
    end)
  end)

  describe('reduce', function()
    it('should fold with an initial value', function()
      expect(Seq({1, 2, 3, 4}):reduce(function(a, b) return a + b end, 0))
        .to.be_equal_to(10)
    end)

    it('should fold using first element as init when none given', function()
      expect(Seq({1, 2, 3}):reduce(function(a, b) return a + b end))
        .to.be_equal_to(6)
    end)

    it('should raise on empty without init', function()
      expect(function()
        Seq({}):reduce(function(a, b) return a + b end)
      end).to.throw()
    end)
  end)

  describe('numeric terminators', function()
    it('sum should add numeric elements', function()
      expect(Seq({1, 2, 3, 4}):sum()).to.be_equal_to(10)
    end)

    it('product should multiply numeric elements', function()
      expect(Seq({2, 3, 4}):product()).to.be_equal_to(24)
    end)

    it('min should return the smallest element', function()
      expect(Seq({3, 1, 4, 1, 5}):min()).to.be_equal_to(1)
    end)

    it('max should return the largest element', function()
      expect(Seq({3, 1, 4, 1, 5}):max()).to.be_equal_to(5)
    end)

    it('min and max return nil for empty', function()
      expect(Seq({}):min()).to.be_nil()
      expect(Seq({}):max()).to.be_nil()
    end)
  end)

  describe('boolean / search terminators', function()
    it('any returns true when at least one element matches', function()
      expect(Seq({1, 2, 3}):any(function(v) return v > 2 end))
        .to.be_true()
      expect(Seq({1, 2, 3}):any(function(v) return v > 10 end))
        .to.be_false()
    end)

    it('all returns true when every element matches', function()
      expect(Seq({2, 4, 6}):all(function(v) return v % 2 == 0 end))
        .to.be_true()
      expect(Seq({2, 3, 6}):all(function(v) return v % 2 == 0 end))
        .to.be_false()
    end)

    it('none returns true when no element matches', function()
      expect(Seq({1, 2, 3}):none(function(v) return v > 10 end))
        .to.be_true()
    end)

    it('find returns the first matching element', function()
      expect(Seq({1, 2, 3, 4}):find(function(v) return v > 2 end))
        .to.be_equal_to(3)
    end)

    it('find returns nil on no match', function()
      expect(Seq({1, 2}):find(function(v) return v > 10 end))
        .to.be_nil()
    end)
  end)

  describe('first / last / count', function()
    it('first returns the first element', function()
      expect(Seq({'a', 'b', 'c'}):first()).to.be_equal_to('a')
    end)

    it('first returns nil on empty', function()
      expect(Seq({}):first()).to.be_nil()
    end)

    it('last returns the last element', function()
      expect(Seq({'a', 'b', 'c'}):last()).to.be_equal_to('c')
    end)

    it('count returns the total', function()
      expect(Seq({1, 2, 3, 4}):count()).to.be_equal_to(4)
    end)
  end)

  describe('for_each', function()
    it('should call fn for each element', function()
      local out = {}
      Seq({1, 2, 3}):for_each(function(v) out[#out + 1] = v end)
      expect(#out).to.be_equal_to(3)
      expect(out[2]).to.be_equal_to(2)
    end)
  end)

  describe('iteration protocol', function()
    it('should work in a for loop', function()
      local seen = {}
      for i, v in Seq({10, 20, 30}) do
        seen[i] = v
      end
      expect(seen[1]).to.be_equal_to(10)
      expect(seen[3]).to.be_equal_to(30)
    end)
  end)
end)

if llx.main_file() then
  os.exit(unit.run_unit_tests() == 0)
end
