local llx = require 'llx'
local unit = require 'llx.unit'

_ENV = unit.create_test_env(_ENV)

describe('Mock', function()
  describe('basic functionality', function()
    it('should track call count', function()
      local m = Mock()
      expect(m:mock_get_call_count()).to.be_equal_to(0)
      m()
      expect(m:mock_get_call_count()).to.be_equal_to(1)
      m()
      expect(m:mock_get_call_count()).to.be_equal_to(2)
    end)

    it('should track call arguments', function()
      local m = Mock()
      m('a', 'b')
      m(1, 2, 3)
      local calls = m:mock_get_calls()
      expect(#calls).to.be_equal_to(2)
      expect(calls[1].args[1]).to.be_equal_to('a')
      expect(calls[1].args[2]).to.be_equal_to('b')
      expect(calls[2].args[1]).to.be_equal_to(1)
      expect(calls[2].args[2]).to.be_equal_to(2)
      expect(calls[2].args[3]).to.be_equal_to(3)
    end)

    it('should preserve nil in arguments using .n', function()
      local m = Mock()
      m(1, nil, 3)
      local call = m:mock_get_last_call()
      expect(call.args.n).to.be_equal_to(3)
      expect(call.args[1]).to.be_equal_to(1)
      expect(call.args[2]).to.be_nil()
      expect(call.args[3]).to.be_equal_to(3)
    end)

    it('should return default return value', function()
      local m = Mock(42)
      local result = m()
      expect(result).to.be_equal_to(42)
    end)

    it('should support mock_return_value', function()
      local m = Mock()
      m:mock_return_value(99)
      expect(m()).to.be_equal_to(99)
    end)

    it('should support mock_return_value_once', function()
      local m = Mock()
      m:mock_return_value(0)
      m:mock_return_value_once(1)
      m:mock_return_value_once(2)
      expect(m()).to.be_equal_to(1)
      expect(m()).to.be_equal_to(2)
      expect(m()).to.be_equal_to(0)
    end)

    it('should support mock_implementation', function()
      local m = Mock()
      m:mock_implementation(function(x) return x * 2 end)
      expect(m(5)).to.be_equal_to(10)
    end)

    it('should support mock_implementation_once', function()
      local m = Mock()
      m:mock_return_value(0)
      m:mock_implementation_once(function() return 'once' end)
      expect(m()).to.be_equal_to('once')
      expect(m()).to.be_equal_to(0)
    end)

    it('should support mock_clear', function()
      local m = Mock()
      m()
      m()
      expect(m:mock_get_call_count()).to.be_equal_to(2)
      m:mock_clear()
      expect(m:mock_get_call_count()).to.be_equal_to(0)
    end)

    it('should support mock_reset', function()
      local m = Mock()
      m:mock_return_value(42)
      m()
      m:mock_reset()
      expect(m:mock_get_call_count()).to.be_equal_to(0)
      expect(m()).to.be_nil()
    end)

    it('should get specific call by index', function()
      local m = Mock()
      m('first')
      m('second')
      m('third')
      expect(m:mock_get_call(1).args[1]).to.be_equal_to('first')
      expect(m:mock_get_call(2).args[1]).to.be_equal_to('second')
      expect(m:mock_get_call(3).args[1]).to.be_equal_to('third')
    end)

    it('should get last call', function()
      local m = Mock()
      m('first')
      m('last')
      expect(m:mock_get_last_call().args[1]).to.be_equal_to('last')
    end)

    it('should track return values in call history', function()
      local m = Mock()
      m:mock_return_value(42)
      m()
      expect(m:mock_get_last_call().return_value).to.be_equal_to(42)
    end)

    it('should support mock_return_value_sequence', function()
      local m = Mock()
      m:mock_return_value_sequence({10, 20, 30})
      expect(m()).to.be_equal_to(10)
      expect(m()).to.be_equal_to(20)
      expect(m()).to.be_equal_to(30)
    end)

    it('should support mock_name', function()
      local m = Mock()
      m:mock_name('myMock')
      expect(m._name).to.be_equal_to('myMock')
    end)

    it('should support chaining', function()
      local m = Mock()
      local result = m:mock_return_value(1):mock_name('chain')
      expect(result).to.be_equal_to(m)
    end)
  end)

  describe('mock matchers', function()
    it('should detect called mock with have_been_called', function()
      local m = Mock()
      m()
      expect(m).to.have_been_called()
    end)

    it('should detect uncalled mock with to_not.have_been_called', function()
      local m = Mock()
      expect(m).to_not.have_been_called()
    end)

    it('should verify call count with have_been_called_times', function()
      local m = Mock()
      m()
      m()
      m()
      expect(m).to.have_been_called_times(3)
    end)

    it('should verify call arguments with have_been_called_with', function()
      local m = Mock()
      m('hello', 42)
      expect(m).to.have_been_called_with('hello', 42)
    end)

    it('should verify last call arguments with '
      .. 'have_been_last_called_with', function()
      local m = Mock()
      m('first')
      m('last')
      expect(m).to.have_been_last_called_with('last')
    end)

    it('should verify nth call arguments with '
      .. 'have_been_nth_called_with', function()
      local m = Mock()
      m('a')
      m('b')
      m('c')
      expect(m).to.have_been_nth_called_with(2, 'b')
    end)

    it('should handle nil arguments in have_been_called_with', function()
      local m = Mock()
      m(nil, 'x')
      expect(m).to.have_been_called_with(nil, 'x')
    end)

    it('should handle matcher arguments in have_been_called_with', function()
      local matchers_mod = require 'llx.unit.matchers'
      local m = Mock()
      m(42)
      expect(m).to.have_been_called_with(matchers_mod.greater_than(40))
    end)

    it('should fail have_been_called_with for non-matching args', function()
      local m = Mock()
      m('a')
      local ok = pcall(function()
        expect(m).to.have_been_called_with('b')
      end)
      expect(ok).to.be_false()
    end)

    it('should support negated mock matchers', function()
      local m = Mock()
      m('a')
      expect(m).to_not.have_been_called_with('b')
      expect(m).to_not.have_been_called_times(5)
    end)
  end)

  describe('return value matchers', function()
    it('should detect returned value with have_returned', function()
      local m = Mock()
      m:mock_return_value(42)
      m()
      expect(m).to.have_returned()
    end)

    it('should fail have_returned when no return value', function()
      local m = Mock()
      m()
      local ok = pcall(function()
        expect(m).to.have_returned()
      end)
      expect(ok).to.be_false()
    end)

    it('should verify specific return value with have_returned_with', function()
      local m = Mock()
      m:mock_return_value(42)
      m()
      expect(m).to.have_returned_with(42)
    end)

    it('should fail have_returned_with for non-matching return', function()
      local m = Mock()
      m:mock_return_value(42)
      m()
      local ok = pcall(function()
        expect(m).to.have_returned_with(99)
      end)
      expect(ok).to.be_false()
    end)

    it('should verify last return value with '
      .. 'have_last_returned_with', function()
      local m = Mock()
      m:mock_return_value_once(1)
      m:mock_return_value_once(2)
      m()
      m()
      expect(m).to.have_last_returned_with(2)
    end)

    it('should verify nth return value with have_nth_returned_with', function()
      local m = Mock()
      m:mock_return_value_once(10)
      m:mock_return_value_once(20)
      m:mock_return_value_once(30)
      m()
      m()
      m()
      expect(m).to.have_nth_returned_with(1, 10)
      expect(m).to.have_nth_returned_with(2, 20)
      expect(m).to.have_nth_returned_with(3, 30)
    end)

    it('should support negated return value matchers', function()
      local m = Mock()
      m:mock_return_value(42)
      m()
      expect(m).to_not.have_returned_with(99)
    end)
  end)
end)

describe('spy_on', function()
  it('should spy on object methods', function()
    local obj = {greet = function(name) return 'hello ' .. name end}
    local spy = spy_on(obj, 'greet')
    local result = obj.greet('world')
    expect(result).to.be_equal_to('hello world')
    expect(spy).to.have_been_called_times(1)
    expect(spy).to.have_been_called_with('world')
    spy:mock_restore()
  end)

  it('should allow overriding return value', function()
    local obj = {method = function() return 'original' end}
    local spy = spy_on(obj, 'method')
    spy:mock_return_value('mocked')
    expect(obj.method()).to.be_equal_to('mocked')
    spy:mock_restore()
  end)

  it('should restore original method with mock_restore', function()
    local original_fn = function() return 'original' end
    local obj = {method = original_fn}
    local spy = spy_on(obj, 'method')
    obj.method()
    spy:mock_restore()
    expect(obj.method).to.be_equal_to(original_fn)
  end)

  it('should auto-restore spies via restore_all_spies', function()
    local original_fn = function() return 'original' end
    local obj = {method = original_fn}
    spy_on(obj, 'method')
    obj.method()
    restore_all_spies()
    expect(obj.method).to.be_equal_to(original_fn)
  end)

  it('should error when method does not exist', function()
    local obj = {}
    local ok = pcall(function()
      spy_on(obj, 'missing')
    end)
    expect(ok).to.be_false()
  end)

  it('should error when target is not a function', function()
    local obj = {value = 42}
    local ok = pcall(function()
      spy_on(obj, 'value')
    end)
    expect(ok).to.be_false()
  end)
end)

if llx.main_file() then
  unit.run_unit_tests()
end
